name: CI Workflow

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Mise à jour vers v3
        with:
          node-version: '16'  # Ou tu peux utiliser '20' si nécessaire

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
